/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "player1_rpc.h"
#include "game.h"
#include "moveball.h"

extern SDL_TimerID timer;
extern PPong_Game game;

int *
launchballp1_1_svc(void *argp, struct svc_req *rqstp)
{
	

  static int  tmr;
  SDL_RemoveTimer(timer);
                                            
  timer = SDL_AddTimer(BSPEED, MoveBall, &game);  
  
    if(timer)
        tmr = 1;
    else
        tmr = 0;  
  
  return &tmr;


}

int *
getrack1_1_svc(int *argp, struct svc_req *rqstp)
{
    static int pos;
    pos = (int)(game.table.rack1.position.x);
    
    if(argp != NULL)
        game.table.rack2.position.x = (*argp);
    
    return &pos;
}

