/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "player1_rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int register_player1_service();

static void
player1prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int getrack1_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case LAUNCHBALLP1:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) launchballp1_1_svc;
		break;

	case GETRACK1:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) getrack1_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}


int register_player1_service()
{
     register SVCXPRT *transp;
	pmap_unset (PLAYER1PROG, PLAYER1VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		return 0;
	}
	if (!svc_register(transp, PLAYER1PROG, PLAYER1VERS, player1prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PLAYER1PROG, PLAYER1VERS, udp).");
		return 0;
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PLAYER1PROG, PLAYER1VERS, player1prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PLAYER1PROG, PLAYER1VERS, tcp).");
		return 0;
	}
	return 1;
}

