/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLAYER2_RPC_H_RPCGEN
#define _PLAYER2_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PLAYER2PROG 0x3FFFFFFF
#define PLAYER2VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LAUNCHBALLP2 1
extern  int * launchballp2_1(void *, CLIENT *);
extern  int * launchballp2_1_svc(void *, struct svc_req *);
extern int player2prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LAUNCHBALLP2 1
extern  int * launchballp2_1();
extern  int * launchballp2_1_svc();
extern int player2prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLAYER2_RPC_H_RPCGEN */
