/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "player2_rpc.h"
#include "game.h"
#include "moveball.h"

extern SDL_TimerID timer;
extern PPong_Game game;

int *
launchballp2_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  tmr;

  SDL_RemoveTimer(timer);
                                            
  timer = SDL_AddTimer(BSPEED, MoveBall, &game);  
  
    if(timer)
        tmr = 1;
    else
        tmr = 0; 

	return &tmr;
}

